### ISSUE TITLE
Some cards dont have English translation data

### ISSUE THREAD

**Issue by kamishirorui** [enstars/makotools#15]
This happened while merging data from the EN Wiki, no idea why sometimes it doesnt match. 

Cards affected: 
![image](https://user-images.githubusercontent.com/58155530/178715952-c62dad26-5680-44fb-b402-acebdde8826e.png)

Fix: Either manually, or I'll find why it doesnt match.

**Comment by neeneemi** [comment]
cards 2197 (meowsketeer ritsu) and 2463 (uta no ojisan) had translation data already, so data for the rest of the cards has been added
