### ISSUE TITLE
Refreshing /cards throws serverless function error

### ISSUE THREAD

**Issue by kamishirorui** [enstars/makotools#24]
> hard refreshing the /cards page (command+r) crashes the server? the page says "This Serverless Function has crashed." and offers a link to this page for site owners to fix the error: https://vercel.com/docs/error/application/FUNCTION_INVOCATION_FAILED

**Comment by kamishirorui** [comment]
@myang5 did that bug fix you do also fix this or was that a separate bug

**Comment by myang5** [comment]
@kamishirorui this one? https://github.com/enstars/makotools/issues/17
I think that PR still didn't fix the crashing on the `/cards` home route

**Comment by kamishirorui** [comment]
oh hold on ye i fixed it a while back, it was bc payload was too large so i added `fields` when using getLocalizedData. is fixed :tomoyay:
