### ISSUE TITLE
Sign in with Google not working

### ISSUE THREAD

**Issue by kamishirorui** [enstars/makotools#26]
whyyyyyyyyy

**Comment by myang5** [comment]
Google sign-in technically works (at least locally) but the current `authDomain` used seems to have a faulty SSL certificate causing the browser to throw a warning that you have to bypass, which is not great:
![IMG_9162](https://user-images.githubusercontent.com/19670297/180365470-bbcfaa4a-9dd9-4b51-9bde-3009a33f67e9.png)
