### ISSUE TITLE
Login page menu is acting strange

### ISSUE THREAD

**Issue by neeneemi** [enstars/makotools#33]
![image](https://user-images.githubusercontent.com/107583604/179744207-b5904156-e320-469a-bb95-4288324475b2.png)

Similar issue to [the homepage](https://github.com/enstars/makotools/issues/27) but worse since the login page is short

**Comment by kamishirorui** [comment]
would prefer smth like `hideFooter`, a `hideHeader` prop on `Layout` for special pages like these @neeneemi
