### ISSUE TITLE
Question(s) 

### ISSUE THREAD

**Issue by ElreamtheFunnyShark** [enstars/makotools#62]
So I recently found out about this project and have been pretty hype about the potential for this and im just a sucker for gacha game tutorials. But I do have some questions that may be too early to ask but im gonna do anyway in case:
1. Will stories from Basic! be translated (or at least briefly summarized) in the site or will it only be Music!! ? Considering the multiple references from Basic! in Music!! ?
2. Also I forgot to mention but are stories going to be translated this time? or will it not happen sadly due to the past deletion on the fandom wiki.

Overall pretty exciting to see where it’s going (and yes I made this account just for this)
Some suggestions that hopefully you guys are adding or planning to hopefully:
-Translated Character introductions in the idol profile (where there is a audio of the character themself and another character’s introduction of said character).
-A forum categories in the site (like the SCP wiki)
-Short video or GIF of character SPP in action (highly unlikely but will honestly be amazingu but then again I understand that would be difficult)
-Basic chibis (I just think their a very cute to be in a card page at least)

Sorry but I’m just excited and I’m really looking forward to how this site grows (also as of currently typing the main page seems to crash a lot so that needs fixing.

Edit: My user is ElreamtheShark as you can tell by similarity

**Comment by kamishirorui** [comment]
SORRY i saw this but i forgot to reply

- we're probably not going to be hosting translations! we're seeing how we can safely share translations but at best it would be simply linking to translator's own websites and stuff 
- character intro voice is planned!
- forums would be hell to moderate so we're pretty sure we wont be adding forms or posts in the future 😔 
- SPP videos are banned by content guidelines but we might be able to host the official SPP stills posted on twitter
- chibis are also planned!

thank you for the feedback! we also released a fix for homepage yesterday so hopefully it works now~
