### ISSUE TITLE
A strange thing I noticed

### ISSUE THREAD

**Issue by ElreamtheFunnyShark** [enstars/makotools#67]
I don’t have discord so I may not understand but why did the events got changed to Japanese? I noticed this today when I went to the site and saw the next door event being in Japanese even when the current event scouts are in English, so I went to check the calendar and also notice that all events are now in Japanese too. 

I’m curious if this is some sort of bug or maybe you guys changed it but I wonder why though ? Hopefully this gets answered and have a good day!

**Comment by kamishirorui** [comment]
Here! https://twitter.com/es_makotools/status/1587426638706671616

> 🔹We're going through some database structure changes, so content may appear in Japanese for a short period of time—This will be fixed in the next patch!
